[build]
  # Forces the build process to start here.
  base = "ceylon-trails"
  # This runs the command *inside* the base directory.
  command = "CI= npm run build"
  # This tells Netlify to publish the 'build' folder *inside* the base directory.
  publish = "build"

# Critical rewrite rule for React client-side routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200